JooleProject/Controllers/HomeController.cs
//using JooleProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;

namespace JooleProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel user)
        {
            UserLogic Ulogic = new UserLogic();
            var myUser = Ulogic.GetIQUsers();
            
            if (ModelState.IsValid)
            {
                
                    var objUser = myUser.Where(a => a.Username.Equals(user.Username) && a.Password.Equals(user.Password)).FirstOrDefault();
                    if (objUser != null)
                    {
                        Session["UserID"] = objUser.UserID.ToString();
                        Session["Username"] = objUser.Username.ToString();
                        return RedirectToAction("Index", "Search");
                    }
                    else
                    {
                        //If the username and password combination is not present in DB then error message is shown.
                        ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                        return RedirectToAction("Index", "Home");
                    }
                
            }

            return View(user);
        }

        public ActionResult UserDashBoard()
        {
            if (Session["UserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

    }
}

JooleProject/Controllers/tblUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
//using JooleProject.Models;
using BusinessLogic;
using DataAccessLayer;

namespace JooleProject.Controllers
{
    public class tblUsersController : Controller
    {
        UserLogic Ulogic = new UserLogic();
       

        // GET: tblUsers
        public ActionResult Index()
        {
            var myUser = Ulogic.GetIQUsers();
            return View(myUser);
        }

        //// GET: tblUsers/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    tblUser tblUser = db.tblUsers.Find(id);

        //    if (tblUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblUser);
        //}

        // GET: tblUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int UserID, String Username, String Password, String Email, String Photo)
        {
            if (ModelState.IsValid)
            {

                Ulogic.Add(UserID, Username, Password, Email, Photo);
                return RedirectToAction("Index","Home");
            }

            return View();
        }

        //// GET: tblUsers/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tblUser tblUser = db.tblUsers.Find(id);
        //    if (tblUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblUser);
        //}

        //// POST: tblUsers/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "UserID,Username,Password,Email,Photo")] tblUser tblUser)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(tblUser).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(tblUser);
        //}

        //// GET: tblUsers/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tblUser tblUser = db.tblUsers.Find(id);
        //    if (tblUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblUser);
        //}

        //// POST: tblUsers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    tblUser tblUser = db.tblUsers.Find(id);
        //    db.tblUsers.Remove(tblUser);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //    protected override void Dispose(bool disposing)
        //    {
        //        if (disposing)
        //        {
        //            db.Dispose();
        //        }
        //        base.Dispose(disposing);
        //    }
    }
}

JooleProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JooleProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JooleProject/Views/Home/Index.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
@model DataAccessLayer.tblUser

@{
    ViewBag.Title = "Home Page";
    //Layout = "~/Views/Shared/layoutNoNav.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">








<body class="bodyhome">
    <div class="signup">
        @Html.ActionLink("Sign Up", "Create", "tblUsers")
    </div>
    <img src="~/images/LogoBig.png" alt="Sample Photo" class="wrapper" style="padding-bottom:400px" />
    <div class="wrapper">
        <h2 style="text-align:center">Building Product Selection Platform</h2>

        @using (Html.BeginForm("Login", "Home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="login" @*style="background-color:aqua"*@>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @*Show details are saved successfully message*@
                    <div class="col-lg-12">@ViewBag.Message</div>
                </div>

                <div class="divpadding">
                    <div class="input-icons">
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "width100", placeholder = "Username or Email" } })
                        <i class="fa fa-user icon"></i>
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="divpadding">
                    <div class="input-icons">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "width100", placeholder = "Password" } })
                        <i class="fa fa-lock icon"></i>
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="submit-btn">
                    @*<div class="col-md-offset-2 col-md-10">*@
                    <input type="submit" value="Login" class="btn btn-default" />
                    @*</div>*@
                </div>
            </div>
        }
    </div>
</body>
 

JooleProject/Views/Home/UserDashBoard.cshtml
@{
    ViewBag.Title = "UserDashBoard";
}

<fieldset>
    <legend>User DashBoard</legend>

    @if (Session["UserName"] != null)
    {
        <text>
            Welcome @Session["UserName"].ToString()
        </text>
    }
</fieldset>